# Generated by Django 6.1 on 2026-09-20 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='regional_language_preference',
            field=models.CharField(default='en', help_text='Preferred NER language (en, as, bn, hi, mni)', max_length=50),
        ),
        migrations.CreateModel(
            name='CaregiverAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(default='SYSTEM', help_text='INACTIVITY, MISSED_MEDS, SCORE_DROP, FATIGUE, ROUTINE', max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Info / Gentle Notice'), ('MEDIUM', 'Moderate Attention'), ('HIGH', 'High / Immediate Check')], default='MEDIUM', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'caregiver_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('reminder_type', models.CharField(choices=[('MEDICINE', 'Medicine / Prescription'), ('HYDRATION', 'Hydration / Water Intake'), ('ROUTINE', 'Daily Activity / Routine'), ('APPOINTMENT', 'Medical Appointment')], default='ROUTINE', max_length=30)),
                ('time', models.TimeField()),
                ('frequency', models.CharField(default='DAILY', help_text='DAILY, WEEKLY, HOURLY, ONCE', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Special instructions or dosage')),
                ('is_completed_today', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_reminders',
                'ordering': ['time'],
            },
        ),
    ]
