# Generated by Django 5.0.14 on 2026-09-20 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('difficulty_level', models.PositiveSmallIntegerField(default=1, help_text='Suggested level (1-5) this scenario is best used at.')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('as', 'Assamese'), ('bn', 'Bengali'), ('mni', 'Manipuri')], default='en', max_length=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['difficulty_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('score', models.FloatField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('incorrect_answers', models.PositiveIntegerField(default=0)),
                ('hints_used', models.PositiveIntegerField(default=0)),
                ('completion_time', models.PositiveIntegerField(blank=True, help_text='Seconds taken to complete the session.', null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('question_queue', models.JSONField(blank=True, default=list)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.patient')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='game.scenario')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('selected_answer', models.CharField(max_length=255)),
                ('correct', models.BooleanField()),
                ('response_time', models.FloatField(blank=True, help_text='Seconds taken to answer.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.gamesession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.CharField(blank=True, help_text='Emoji, icon name, or path under /assets used to represent this activity.', max_length=255)),
                ('sequence_order', models.PositiveSmallIntegerField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='game.scenario')),
            ],
            options={
                'ordering': ['scenario', 'sequence_order'],
            },
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['patient', '-created_at'], name='game_gamese_patient_9e8ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['scenario', 'sequence_order'], name='game_activi_scenari_519220_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('scenario', 'sequence_order'), name='unique_sequence_order_per_scenario'),
        ),
    ]
