from django.conf import settings
from django.db import models


class PatientProfile(models.Model):
    """Extended profile for patients."""

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='patient_profile',
    )
    emergency_contact_name = models.CharField(max_length=150, blank=True)
    emergency_contact_phone = models.CharField(max_length=20, blank=True)
    medical_notes = models.TextField(
        blank=True,
        help_text='General medical notes (non-diagnostic)',
    )
    regional_language_preference = models.CharField(
        max_length=50,
        default='en',
        help_text='Preferred NER language (en, as, bn, hi, mni)',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'patient_profiles'

    def __str__(self):
        return f'Patient: {self.user.get_full_name()}'


class Reminder(models.Model):
    """
    Reminders for Elderly Patients:
    - MEDICINE: Medication time, dosage, instructions
    - HYDRATION: Water intake prompt
    - ROUTINE: Daily activity (Morning walk, Breakfast, Evening tea, etc.)
    - APPOINTMENT: Medical / Doctor appointment
    """

    class ReminderType(models.TextChoices):
        MEDICINE = 'MEDICINE', 'Medicine / Prescription'
        HYDRATION = 'HYDRATION', 'Hydration / Water Intake'
        ROUTINE = 'ROUTINE', 'Daily Activity / Routine'
        APPOINTMENT = 'APPOINTMENT', 'Medical Appointment'

    patient = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='reminders',
    )
    title = models.CharField(max_length=200)
    reminder_type = models.CharField(
        max_length=30,
        choices=ReminderType.choices,
        default=ReminderType.ROUTINE,
    )
    time = models.TimeField()
    frequency = models.CharField(
        max_length=50,
        default='DAILY',
        help_text='DAILY, WEEKLY, HOURLY, ONCE',
    )
    notes = models.TextField(blank=True, help_text='Special instructions or dosage')
    is_completed_today = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'patient_reminders'
        ordering = ['time']

    def __str__(self):
        return f'{self.title} ({self.reminder_type}) for {self.patient.get_full_name()}'


class CaregiverAlert(models.Model):
    """
    Alerts automatically generated by AI/system for Caregivers and Healthcare Workers.
    e.g., Inactivity in 48h, Missed critical medicines, Significant cognitive score drop.
    """

    class Severity(models.TextChoices):
        LOW = 'LOW', 'Info / Gentle Notice'
        MEDIUM = 'MEDIUM', 'Moderate Attention'
        HIGH = 'HIGH', 'High / Immediate Check'

    patient = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='caregiver_alerts',
    )
    title = models.CharField(max_length=200)
    message = models.TextField()
    alert_type = models.CharField(
        max_length=50,
        default='SYSTEM',
        help_text='INACTIVITY, MISSED_MEDS, SCORE_DROP, FATIGUE, ROUTINE',
    )
    severity = models.CharField(
        max_length=20,
        choices=Severity.choices,
        default=Severity.MEDIUM,
    )
    is_resolved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'caregiver_alerts'
        ordering = ['-created_at']

    def __str__(self):
        return f'[{self.severity}] {self.title} - {self.patient.get_full_name()}'
