# Generated by Django 6.1 on 2026-09-20 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('game_type', models.CharField(choices=[('MEMORY_MATCH', 'Memory Match'), ('PATTERN_SEQUENCE', 'Pattern & Sequence'), ('DAILY_RECALL', 'Daily Recall')], max_length=20, unique=True)),
                ('icon', models.CharField(default='🧠', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveIntegerField()),
                ('config', models.JSONField(default=dict, help_text='Level-specific parameters: num_items, display_time, etc.')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='games.game')),
            ],
            options={
                'db_table': 'game_levels',
                'ordering': ['game', 'level_number'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='Normalized score 0-100', max_digits=5)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, help_text='Accuracy percentage 0-100', max_digits=5)),
                ('response_time_ms', models.PositiveIntegerField(default=0, help_text='Average response time in milliseconds')),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.game')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.gamelevel')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='gamelevel',
            constraint=models.UniqueConstraint(fields=('game', 'level_number'), name='unique_game_level'),
        ),
    ]
